version: '2'
services:
  couch_db:
    image: klaemo/couchdb:2.0-single
    restart: always
    logging:
      driver: 'none'
    ports:
      - '3000:5984'
      - '3010:5984'

  auth_ms:
    image: blinkbox/authentication
    environment:
      DB_PORT: '5984'
      DB_URL: 'couch_db'
      JWT_SECRET: 'ec6607e21b57ac2ccc5836754893ed33'
    ports:
      - '4005:4005'
    links:
      - couch_db

  user_ms:
    image: blinkbox/user-crud
    environment:
      DB_PORT: '5984'
      DB_URL: 'couch_db'
    ports:
      - '4000:4000'
    links:
      - couch_db

  notification_ms:
    image: blinkbox/notification
    environment:
      NAME: "Blinkbox Project"
      USERNAME: "blinkboxunal@gmail.com"
      PASSWORD: "bl1nkb0x"
      EMAIL_SERVER: "smtp.gmail.com"
      PORT: '587'
    ports:
      - '4010:4010'

  api_gateway:
    image: blinkbox/api-gateway
    environment:
      USER_PORT: '4000'
      USER_HOST: 'user_ms'
      AUTH_PORT: '4005'
      AUTH_HOST: 'auth_ms'
      NOTIFICATION_PORT: '4010'
      NOTIFICATION_HOST: 'notification_ms'
      UPDATE_PORT: '4020'
      UPDATE_HOST: 'update_ms'
      DELETE_PORT: '4030'
      DELETE_HOST: 'delete_ms'
      UPLOAD_PORT: '4015'
      UPLOAD_HOST: 'upload_ms'
      ACCESS_PORT: '4025'
      ACCESS_HOST: 'file_access_ms'
    ports:
      - '5000:5000'
    links:
      - user_ms
      - auth_ms
      - notification_ms