version: '2'
services:
  users-db:
    image: klaemo/couchdb:2.0-single
    restart: always
    logging:
      driver: 'none'
    ports:
      - '3000:5984'
    labels:
      io.rancher.scheduler.affinity:host_label: user_db=user_db


  files-db:
    image: klaemo/couchdb:2.0-single
    restart: always
    logging:
      driver: 'none'
    ports:
      - '3010:5984'
    labels:
      io.rancher.scheduler.affinity:host_label: file_db=file_db


  user-ms:
    image: blinkbox/user-crud
    environment:
      DB_PORT: '5984'
      DB_URL: 'users-db'
    ports:
      - '4000:4000'
    links:
      - users-db
    labels:
      io.rancher.scheduler.affinity:host_label: user=user


  auth-ms:
    image: blinkbox/authentication
    environment:
      DB_PORT: '5984'
      DB_URL: 'users-db'
      JWT_SECRET: 'ec6607e21b57ac2ccc5836754893ed33'
    ports:
      - '4005:4005'
    links:
      - users-db
    labels:
      io.rancher.scheduler.affinity:host_label: main=main

  notification-ms:
    image: blinkbox/notification
    environment:
      NAME: 'Blinkbox Project'
      USERNAME: 'blinkboxunal@gmail.com'
      PASSWORD: 'bl1nkb0x'
      EMAIL_SERVER: 'smtp.gmail.com'
      PORT: '587'
    ports:
      - '4010:4010'
    labels:
      io.rancher.scheduler.affinity:host_label: user=user


  update-ms:
    image: blinkbox/update
    environment:
      DB_PORT: '5984'
      DB_URL: 'files-db'
      SECRET_KEY_BASE: '88e17a0d8bc9aaff8b23b3a64921da46059b175d73966151dd10029934cde9d4fa645c55a2a8e71e4a23778e64ce408caf7c4e5ca7c163d3785c9363f1153e4d'
    command: bundle exec rails s -e production -p 4020 -b '0.0.0.0'
    ports:
      - '4020:4020'
    links:
      - files-db
    labels:
      io.rancher.scheduler.affinity:host_label: file=file


  delete-ms:
    image: blinkbox/delete
    environment:
      HOST_PORT: '4030'
      HOST_URL: '0.0.0.0'
      DB_URL: 'files-db'
      DB_PORT: '3010'
      DB_NAME: 'blinkbox_files'
    ports:
      - '4030:4030'
    links:
      - files-db
    labels:
      io.rancher.scheduler.affinity:host_label: file=file


  upload-ms:
    image: blinkbox/upload
    environment:
      HOST_PORT: '4015'
      HOST_URL: '0.0.0.0'
      DB_PORT: '5984'
      DB_URL: 'files-db'
    ports:
      - '4015:4015'
    links:
      - files-db
    labels:
      io.rancher.scheduler.affinity:host_label: file=file


  file-access-ms:
    image: blinkbox/fileaccess
    ports:
      - '4025:4025'
    environment:
      DB_NAME: 'blinkbox_files'
      DB_URL: 'files-db'
      DB_PORT: '5984'
      HOST_PORT: '4025'
      HOST_URL: '0.0.0.0'
    links:
      - files-db
    labels:
      io.rancher.scheduler.affinity:host_label: file=file


  api-gateway:
    image: blinkbox/api-gateway
    environment:
      USER_PORT: '4000'
      USER_HOST: 'user-ms'
      AUTH_PORT: '4005'
      AUTH_HOST: 'auth-ms'
      NOTIFICATION_PORT: '4010'
      NOTIFICATION_HOST: 'notification-ms'
      UPDATE_PORT: '4020'
      UPDATE_HOST: 'update-ms'
      DELETE_PORT: '4030'
      DELETE_HOST: 'delete-ms'
      UPLOAD_PORT: '4015'
      UPLOAD_HOST: 'upload-ms'
      ACCESS_PORT: '4025'
      ACCESS_HOST: 'file-access-ms'
    ports:
      - '5000:5000'
    links:
      - user-ms
      - auth-ms
      - notification-ms
      - update-ms
      - delete-ms
      - upload-ms
      - file-access-ms
    labels:
      io.rancher.scheduler.affinity:host_label: main=main


  frontend-ms:
    image: blinkbox/frontend
    environment:
      BACK_PORT: '5000'
      BACK_URL: 'api-gateway'
      HOST_PORT: '5010'
      HOST_URL: '0.0.0.0'
      FILE_ACCESS: 'file-access-ms'
      UPLOAD: 'upload-ms'
    ports:
      - '5010:5010'
    links:
      - file-access-ms
      - upload-ms
      - api-gateway
    labels:
      io.rancher.scheduler.affinity:host_label: main=main


  server-lb:
    image: rancher/lb-service-haproxy
    ports:
      - "80:80"
    labels:
      io.rancher.scheduler.affinity:host_label: balancer=balancer
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
