users-db:
  scale: 2

files-db:
  scale: 2

user-ms:
  scale: 2

auth-ms:
  scale: 3

notification-ms:
  scale: 2

update-ms:
  scale: 2

delete-ms:
  scale: 2

upload-ms:
  scale: 2

file-access-ms:
  scale: 2

api-gateway:
  scale: 3

frontend-ms:
  scale: 3

blinkbox-lb:
  scale: 1
  lb_config:
    certs: []
    port_rules:
    - priority: 1
      protocol: http
      service: frontend-ms
      source_port: 80
      target_port: 5010
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    port: 42
    unhealthy_threshold: 3
    interval: 2000

# server-lb:
#   scale: 1
#   lb_config:
#     certs: []
#     port_rules:
#     - priority: 1
#       protocol: http
#       service: frontend-ms
#       source_port: 80
#       target_port: 5010
#   health_check:
#     response_timeout: 2000
#     healthy_threshold: 2
#     port: 42
#     unhealthy_threshold: 3
#     interval: 2000
