version: '2'
services:
  couch-db:
    image: klaemo/couchdb:2.0-single
    restart: always
    logging:
      driver: 'none'
    ports:
      - '3001:5984'
      - '3011:5984'

  # Main
  auth-ms:
    image: blinkbox/authentication
    environment:
      HOST_PORT: '4006'
      DB_PORT: '3000'
      DB_URL: '10.0.0.2'
      JWT_SECRET: 'ec6607e21b57ac2ccc5836754893ed33'
    ports:
      - '4006:4006'
    links:
      - couch-db

  api-gateway:
    image: blinkbox/api-gateway
    environment:
      USER_PORT: '4000'
      USER_HOST: '10.0.0.2'
      AUTH_PORT: '4005'
      AUTH_HOST: '10.0.0.2'
      NOTIFICATION_PORT: '4010'
      NOTIFICATION_HOST: '10.0.0.2'
      UPDATE_PORT: '4020'
      UPDATE_HOST: '10.0.0.2'
      DELETE_PORT: '4030'
      DELETE_HOST: '10.0.0.2'
      UPLOAD_PORT: '4015'
      UPLOAD_HOST: '10.0.0.2'
      ACCESS_PORT: '4025'
      ACCESS_HOST: '10.0.0.2'
      HOST_PORT: '5001'
    ports:
      - '5001:5001'
    links:
      - auth-ms

  frontend-ms:
    image: blinkbox/frontend
    environment:
      BACK_PORT: '5000'
      BACK_URL: '10.0.0.2'
      HOST_PORT: '5011'
      HOST_URL: '0.0.0.0'
      FILE_ACCESS: '10.0.0.2'
      UPLOAD: '10.0.0.2'
    ports:
      - '5011:5011'
    links:
      - api-gateway

  # load balancer
  server-lb:
    image: rancher/lb-service-haproxy:v0.4.2
    ports:
      - '80:80'
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create-agent: 'true'
    links:
      - frontend-ms
      - api-gateway
