version: '2'
services:
  couch-db:
    image: klaemo/couchdb:2.0-single
    restart: always
    logging:
      driver: 'none'
    ports:
      - '3000:5984'
      - '3010:5984'

  auth-ms:
    image: blinkbox/authentication
    environment:
      DB-PORT: '5984'
      DB-URL: 'couch-db'
      JWT-SECRET: 'ec6607e21b57ac2ccc5836754893ed33'
    ports:
      - '4005:4005'
    links:
      - couch-db

  api-gateway:
    image: blinkbox/api-gateway
    environment:
      USER-PORT: '4000'
      USER-HOST: 'user-ms'
      AUTH-PORT: '4005'
      AUTH-HOST: 'auth-ms'
      NOTIFICATION-PORT: '4010'
      NOTIFICATION-HOST: 'notification-ms'
      UPDATE-PORT: '4020'
      UPDATE-HOST: 'update-ms'
      DELETE-PORT: '4030'
      DELETE-HOST: 'delete-ms'
      UPLOAD-PORT: '4015'
      UPLOAD-HOST: 'upload-ms'
      ACCESS-PORT: '4025'
      ACCESS-HOST: 'file-access-ms'
    ports:
      - '5000:5000'
    links:
      - auth-ms
  bank-lb:
    image: rancher/lb-service-haproxy:v0.4.2
    ports:
      - "80:80"
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create-agent: 'true'
    links:
      - frontend-ms
  frontend-ms:
    image: blinkbox/frontend
    ports:
      - "85:85"
