version: '2'
services:
  couch_db:
    image: klaemo/couchdb:2.0-single
    restart: always
    logging:
      driver: 'none'
    ports:
      - '3000:5984'
      - '3010:5984'

  auth_ms:
    image: blinkbox/authentication
    environment:
      DB_PORT: '5984'
      DB_URL: 'couch_db'
      JWT_SECRET: 'ec6607e21b57ac2ccc5836754893ed33'
    ports:
      - '4005:4005'
    links:
      - couch_db

  api_gateway:
    image: blinkbox/api-gateway
    environment:
      USER_PORT: '4000'
      USER_HOST: 'user_ms'
      AUTH_PORT: '4005'
      AUTH_HOST: 'auth_ms'
      NOTIFICATION_PORT: '4010'
      NOTIFICATION_HOST: 'notification_ms'
      UPDATE_PORT: '4020'
      UPDATE_HOST: 'update_ms'
      DELETE_PORT: '4030'
      DELETE_HOST: 'delete_ms'
      UPLOAD_PORT: '4015'
      UPLOAD_HOST: 'upload_ms'
      ACCESS_PORT: '4025'
      ACCESS_HOST: 'file_access_ms'
    ports:
      - '5000:5000'
    links:
      - auth_ms
      - update_ms
      - delete_ms
      - upload_ms
      - file_access_ms
    labels:
      io.rancher.scheduler.affinity: 'node1'
      io.rancher.scheduler.affinity: 'node2'
  bank-lb:
    image: rancher/lb-service-haproxy:v0.4.2
    ports:
      - "80:80"
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity: 'node1'
  frontend-ms:
    image: blinkbox/frontend
    ports:
      - "85:85"
