couch-db:
  scale: 1
auth-ms:
  scale: 1
api-gateway:
  scale: 1
bank-lb:
  scale: 1
  lb-config:
    certs: []
    port-rules:
    - priority: 1
      protocol: http
      service: frontend-ms
      source-port: 80
      target-port: 85
  health-check:
    response-timeout: 2000
    healthy-threshold: 2
    port: 42
    unhealthy-threshold: 3
    interval: 2000
