auth-ms:
  scale: 2
bank-lb:
  scale: 1
  lb-config:
    certs: []
    port-rules:

      #File access services
      - protocol: http
        service: file-access-ms-2
        source-port: 4025
        target-port: 4026

      - protocol: http
        service: file-access-ms-4
        source-port: 4025
        target-port: 4027
  health-check:
    response-timeout: 2000
    healthy-threshold: 2
    port: 42
    unhealthy-threshold: 3
    interval: 2000
