version: '2'
services:
  users-db:
    image: klaemo/couchdb:2.0-single
    restart: always
    logging:
      driver: 'none'
    ports:
      - '3003:5984'

  # Main
  auth-ms:
    image: blinkbox/authentication
    environment:
      HOST_PORT: '4008'
      DB_PORT: '3000'
      DB_URL: '10.0.0.2'
      JWT_SECRET: 'ec6607e21b57ac2ccc5836754893ed33'
    ports:
      - '4008:4008'

  api-gateway:
    image: blinkbox/api-gateway
    environment:
      USER_PORT: '4000'
      USER_HOST: '10.0.0.2'
      AUTH_PORT: '4005'
      AUTH_HOST: '10.0.0.2'
      NOTIFICATION_PORT: '4010'
      NOTIFICATION_HOST: '10.0.0.2'
      UPDATE_PORT: '4020'
      UPDATE_HOST: '10.0.0.2'
      DELETE_PORT: '4030'
      DELETE_HOST: '10.0.0.2'
      UPLOAD_PORT: '4015'
      UPLOAD_HOST: '10.0.0.2'
      ACCESS_PORT: '4025'
      ACCESS_HOST: '10.0.0.2'
      HOST_PORT: '5003'
    ports:
      - '5003:5003'
    links:
      - user-ms
      - auth-ms
      - notification-ms

  frontend-ms:
    image: blinkbox/frontend
    environment:
      BACK_PORT: '5000'
      BACK_URL: '10.0.0.2'
      HOST_PORT: '5012'
      HOST_URL: '0.0.0.0'
      FILE_ACCESS: '10.0.0.2'
      UPLOAD: '10.0.0.2'
    ports:
      - '5012:5012'
    links:
      - file-access-ms
      - upload-ms
      - api-gateway

  # User
  user-ms:
    image: blinkbox/user-crud
    environment:
      DB_PORT: '3000'
      DB_URL: '10.0.0.2'
      HOST_PORT: '4003'
    ports:
      - '4003:4003'
    links:
      - users-db

  notification-ms:
    image: blinkbox/notification
    environment:
      NAME: 'Blinkbox Project'
      USERNAME: 'blinkboxunal@gmail.com'
      PASSWORD: 'bl1nkb0x'
      EMAIL_SERVER: 'smtp.gmail.com'
      PORT: '587'
      HOST_PORT: '4013'
    ports:
      - '4013:4013'