version: '2'
services:
  users-db:
    image: klaemo/couchdb:2.0-single
    restart: always
    logging:
      driver: 'none'
    ports:
      - '3003:5984'

  # User
  user-ms:
    image: blinkbox/user-crud
    environment:
      DB_PORT: '3000'
      DB_URL: '10.0.0.2'
      HOST_PORT: '4003'
    ports:
      - '4003:4003'
    links:
      - users-db

  notification-ms:
    image: blinkbox/notification
    environment:
      NAME: 'Blinkbox Project'
      USERNAME: 'blinkboxunal@gmail.com'
      PASSWORD: 'bl1nkb0x'
      EMAIL_SERVER: 'smtp.gmail.com'
      PORT: '587'
      HOST_PORT: '4013'
    ports:
      - '4013:4013'