version: '2'
services:
  files-db:
    image: klaemo/couchdb:2.0-single
    restart: always
    logging:
      driver: 'none'
    ports:
      - '3012:5984'

  # Main
  auth-ms:
    image: blinkbox/authentication
    environment:
      HOST_PORT: '4007'
      DB_PORT: '3000'
      DB_URL: '10.0.0.2'
      JWT_SECRET: 'ec6607e21b57ac2ccc5836754893ed33'
    ports:
      - '4007:4007'

  api-gateway:
    image: blinkbox/api-gateway
    environment:
      USER_PORT: '4000'
      USER_HOST: '10.0.0.2'
      AUTH_PORT: '4005'
      AUTH_HOST: '10.0.0.2'
      NOTIFICATION_PORT: '4010'
      NOTIFICATION_HOST: '10.0.0.2'
      UPDATE_PORT: '4020'
      UPDATE_HOST: '10.0.0.2'
      DELETE_PORT: '4030'
      DELETE_HOST: '10.0.0.2'
      UPLOAD_PORT: '4015'
      UPLOAD_HOST: '10.0.0.2'
      ACCESS_PORT: '4025'
      ACCESS_HOST: '10.0.0.2'
      HOST_PORT: '5002'
    ports:
      - '5002:5002'
    links:
      - auth-ms
      - update-ms
      - delete-ms
      - upload-ms
      - file-access-ms

  frontend-ms:
    image: blinkbox/frontend
    environment:
      BACK_PORT: '5000'
      BACK_URL: '10.0.0.2'
      HOST_PORT: '5012'
      HOST_URL: '0.0.0.0'
      FILE_ACCESS: '10.0.0.2'
      UPLOAD: '10.0.0.2'
    ports:
      - '5012:5012'
    links:
      - file-access-ms
      - upload-ms
      - api-gateway

  # File
  update-ms:
    image: blinkbox/update
    environment:
      DB_PORT: '3010'
      DB_URL: '10.0.0.2'
      SECRET_KEY_BASE: '88e17a0d8bc9aaff8b23b3a64921da46059b175d73966151dd10029934cde9d4fa645c55a2a8e71e4a23778e64ce408caf7c4e5ca7c163d3785c9363f1153e4d'
    command: bundle exec rails s -e production -p 4022 -b '0.0.0.0'
    volumes:
      - .:/update
    ports:
      - '4022:4022'
    links:
      - files-db

  delete-ms:
    image: blinkbox/delete
    environment:
      HOST_PORT: '4032'
      HOST_URL: '0.0.0.0'
      DB_URL: '10.0.0.2'
      DB_PORT: '3010'
      DB_NAME: 'blinkbox_files'
    ports:
      - '4032:4032'
    links:
      - files-db

  upload-ms:
    image: blinkbox/upload
    environment:
      HOST_PORT: '4017'
      HOST_URL: '0.0.0.0'
      DB_PORT: '3010'
      DB_URL: '10.0.0.2'
    ports:
      - '4017:4017'
    links:
      - files-db

  file-access-ms:
    image: blinkbox/fileaccess
    ports:
      - '4027:4027'
    environment:
      DB_NAME: 'blinkbox_files'
      DB_URL: '10.0.0.2'
      DB_PORT: '3010'
      HOST_PORT: '4027'
      HOST_URL: '0.0.0.0'
    links:
      - files-db