version: '2'
services:
  users_db:
    image: klaemo/couchdb:2.0-single
    logging:
      driver: 'none'
    ports:
      - '3000:5984'
    volumes:
      - ./users_db_data:/usr/local/var/lib/couchdb/

  user_ms:
    image: blinkbox/user-crud
    environment:
      DB_PORT: '5984'
      DB_URL: 'users_db'
    ports:
      - '4000:4000'
    links:
      - users_db

  auth_ms:
    image: blinkbox/authentication
    environment:
      DB_PORT: '5984'
      DB_URL: 'users_db'
      JWT_SECRET: 'ec6607e21b57ac2ccc5836754893ed33'
    ports:
      - '4005:4005'
    links:
      - users_db

  notification_ms:
    image: blinkbox/notification
    environment:
      NAME: "Blinkbox Project"
      USERNAME: "blinkboxunal@gmail.com"
      PASSWORD: "bl1nkb0x"
      EMAIL_SERVER: "smtp.gmail.com"
      PORT: '587'
    ports:
      - '4010:4010'

  files_db:
    image: klaemo/couchdb:2.0-single
    logging:
          driver: 'none'
    ports:
      - '3010:5984'
    volumes:
      - ./files_db_data:/usr/local/var/lib/couchdb/
  
  file_access_ms:
    image: blinkbox/fileaccess
    ports:
      - '4025:4025'
    environment:
      DB_NAME: 'blinkbox_files'
      DB_URL: 'files_db'
      DB_PORT: '5984'
      HOST_PORT: '4025'
      HOST_URL: '0.0.0.0'
    links:
      - files_db

  api_gateway:
    image: blinkbox/api-gateway
    environment:
      USER_PORT: '4000'
      USER_HOST: 'user_ms'
      AUTH_PORT: '4005'
      AUTH_HOST: 'auth_ms'
      NOTIFICATION_PORT: '4010'
      NOTIFICATION_HOST: 'notification_ms'
      ACCESS_PORT: '4025'
      ACCESS_HOST: 'file_access_ms'
    ports:
      - '5000:5000'
    links:
      - user_ms
      - auth_ms
      - notification_ms
      - file_access_ms

  upload_ms:
    image: blinkbox/upload
    environment:
        DB_PORT: '5984'
        DB_URL: 'files_db'
        DB_NAME: 'blinkbox_files'
        HOST_URL: '0.0.0.0'
        HOST_PORT: '4015'
    ports:
      - "4015:4015"
    links:
      - files_db

  frontend-ms:
    image: blinkbox/frontend
    environment:
      BACK_PORT: "5000"
      BACK_URL: "0.0.0.0"
      HOST_PORT: "5010"
      HOST_URL: "0.0.0.0"
      FILE_ACCESS: "0.0.0.0" #Need to be changed, maybe
      UPLOAD: "0.0.0.0" #Need to be changed, maybe
    ports:
      - "5010:5010"
    links:
      - file_access_ms
      - upload_ms
      - api_gateway
    labels:
      io.rancher.scheduler.affinity:host_label: main=main
